//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fund.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int IDBook { get; set; }
        public Nullable<System.DateTime> DateOfReceipt { get; set; }
        public Nullable<int> IDGenre { get; set; }
        public string AuthorName { get; set; }
        public string BookTitle { get; set; }
        public Nullable<int> PublicationYear { get; set; }
        public Nullable<bool> IsInMandatoryReadingList { get; set; }
    
        public virtual Genres Genres { get; set; }
    }
}
