//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Солнышко.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SunEntities : DbContext
    {
        public SunEntities()
            : base("name=SunEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Direction> Direction { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Journal> Journal { get; set; }
        public virtual DbSet<Mark> Mark { get; set; }
        public virtual DbSet<ViewGroup> ViewGroup { get; set; }
    }
}
