//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int IDMaterial { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int IDManufacturer { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
