//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int IDJournal { get; set; }
        public System.DateTime DateStart { get; set; }
        public int IDViewAnimal { get; set; }
        public string Nickname { get; set; }
        public bool Passport { get; set; }
        public int Age { get; set; }
        public string Service { get; set; }
        public System.DateTime DateEnd { get; set; }
    
        public virtual ViewAnimal ViewAnimal { get; set; }
    }
}
